### ISSUE TITLE
Query parameters are ignored when using broker

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#709] opened 2016-08-31 19:31 UTC
We acquire token with query params: "nux=1&msafed=0" to avoid seeing picker in Web view. And it works for regular flow, but it's ignored for broker flow.

**Comment by weijjia** [comment] 2016-10-18 05:48
@imakhalova Can you get us a trace for this?

**Comment by imakhalova** [comment] 2016-10-18 20:09
fiddler trace? logs?
Here is repro steps:
1) install broker app
2) within your test app setUseBroker and acqiureToken with passing something in argument String extraQueryParameters
Actual uri that invoked in broker app won't have that query parameter

**Comment by weijjia** [comment] 2016-10-18 20:12
It would be nice if you can share a fiddler trace. I did a test with the test app by passing some extra param and I'm seeing the query param passed into broker and trace i have actually has the passed in extra param. My thought is that if when we force a broker RT acquisition, the query param could be dropped. I can share my trace which has the extra qp if you want.

**Comment by imakhalova** [comment] 2016-10-18 21:08
Here is the same request that we send w/o broker:
GET /common/oauth2/authorize?response_type=code&client_id=b26aadf8-566f-4478-926f-589f601d9c74&resource=https%3A%2F%2Fofficeapps.live.com&redirect_uri=msauth%3A%2F%2Fcom.microsoft.skydrive%2FODD3OR3tCemNTgxEX1K6yZVHByw%253D&state=YT1odHRwczovL2xvZ2luLndpbmRvd3MubmV0L2NvbW1vbiZyPWh0dHBzOi8vb2ZmaWNlYXBwcy5saXZlLmNvbQ&login_hint=imakhal%40microsoft.com&x-client-SKU=Android&x-client-Ver=1.10.0&x-client-OS=23&x-client-DM=Nexus+6P&client-request-id=e59cb52c-aa67-4d25-aded-2394c32ef738&prompt=login&haschrome=1&nux=1&msafed=0 HTTP/1.1
with broker:
GET /common/oauth2/authorize?response_type=code&client_id=b26aadf8-566f-4478-926f-589f601d9c74&resource=https%3A%2F%2Fofficeapps.live.com&redirect_uri=msauth%3A%2F%2Fcom.microsoft.skydrive%2FODD3OR3tCemNTgxEX1K6yZVHByw%253D&state=YT1odHRwczovL2xvZ2luLndpbmRvd3MubmV0L2NvbW1vbiZyPWh0dHBzOi8vb2ZmaWNlYXBwcy5saXZlLmNvbQ&login_hint=imakhal%40microsoft.com&x-client-SKU=Android&x-client-Ver=1.2.0&x-client-brkrver=v2.0.0&x-client-OS=23&x-client-DM=Nexus+6P&client-request-id=a699b3d9-2b57-49df-a621-3a781251b44c&prompt=login&nux=1&restrict_to_hint=true&brkr=1 HTTP/1.1

And we actually send query params "nux=1&msafed=0"
I see that nux=1 was passed while msafed=0 was lost.

**Comment by weijjia** [comment] 2016-10-19 02:07
I got it, I was using a different version which has some change around the passed-in extra query string. You're right, with the current broker version, yes, broker is dropping the query parameters. For "nux=1", broker passed it in by default. Here is our thought, for query parameter i.e. "msfed=0", which is to block sign-in with MFA guest account. However, broker is caching based on user and is a central storage for different apps, some apps may want to block the sign-in with MFA guest account while others don't, we need more discussions around the behavior. So the conclusion is, the current behavior is by design.

**Comment by imakhalova** [comment] 2016-10-19 04:42
This query parameter shouldn't break caching: if 1 app passes query argument Broker should invoke browser with that argument, if another app doesn't pass arguments then broker should invoke browser without arguments and get another web response

**Comment by weijjia** [comment] 2017-02-16 21:57
Fixed in the current playstore version of broker.

**Closed by weijjia** 2017-02-16 21:57 UTC
Labels: P1
