### ISSUE TITLE
Fix the ignored unit tests caused by the unified/dev Merge

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/azure-activedirectory-library-for-android#1186] opened 2018-05-15 20:51 UTC
There are couple of unit tests ignored in the unified/dev. @iambmelt should have detailed context why these unit tests are skip for now as well as the future plan of them.

- testScenarioEmptyIdToken
- testNewTokenOnlyWrittenToPreferredCacheLocation
- testGetChallengeResponseInvalidRedirect

RFC #1184

**Comment by iambmelt** [comment] 2019-12-19 22:55
Working as intended. CLosing

**Closed by iambmelt** 2019-12-19 22:55 UTC
