### ISSUE TITLE
ANRs detected in AadIdentityProvider

### ISSUE THREAD

**Issue by jiaxh** [AzureAD/azure-activedirectory-library-for-android#1161] opened 2018-03-29 05:46 UTC
Please ensure the following information is provided when logging a new issue:

<ul>
  <li>The ANR doesn't happen</li>
  <li>ANRs detected and reported to Google play console</li>
  <li>com.microsoft.aad:adal:1.13.3</li>
</ul>

Anr information and stack is attached as below

"main" prio=5 tid=1 Blocked | group="main" sCount=1 dsCount=0 obj=0x746df670 self=0xe7b05400 | sysTid=4679 nice=-10 cgrp=default sched=0/0 handle=0xea7ba534 | state=S schedstat=( 445633906 59719691 458 ) utm=28 stm=16 core=4 HZ=100 | stack=0xff579000-0xff57b000 stackSize=8MB | held mutexes=
at android.app.ContextImpl.getPreferencesDir (ContextImpl.java:464)
- waiting to lock <0x001bc3f1> (a java.lang.Object) held by thread 20
at android.app.ContextImpl.getSharedPreferencesPath (ContextImpl.java:627)
at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:345)
- locked <0x0eec0bd6> (a java.lang.Class<android.app.ContextImpl>)
at android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:164)
at com.microsoft.aad.adal.DefaultTokenCacheStore.<init> (DefaultTokenCacheStore.java:98)
at com.microsoft.aad.adal.AuthenticationContext.<init> (AuthenticationContext.java:101)
at com.microsoft.aad.adal.ADALAuthenticationContext.<init> (ADALAuthenticationContext.java:11)
at com.microsoft.launcher.identity.MRRTAADIdentityProvider.e (MRRTAADIdentityProvider.java:116)
at com.microsoft.launcher.identity.MRRTAADIdentityProvider.<init> (MRRTAADIdentityProvider.java:106)
at com.microsoft.launcher.identity.a.<init> (AadIdentityProvider.java:14)

**Comment by iambmelt** [comment] 2018-03-29 14:29
I suspect this issue could be a combination of things:
 - This call ANR'd on the constructor call to `AuthenticationContext` which can be initialized either on or off the UI thread (this is left to the discretion of the implementer)
- [`StrictMode`](https://developer.android.com/reference/android/os/StrictMode.html) may be enabled, which could _reasonably_ throw an `ANR` for `ContextImpl.getPreferencesDir()` (although I wouldn't be particularly concerned with this case, as `StrictMode` is, by definition, not intended to replicate _normal_ operation conditions)

@jiaxh If you are a member of the Launcher team and are seeing an excess of these reports, please follow up with our team to share these reports so that we can get more detail. Additionally, please review the initialization of `AuthenticationContext` to ensure that the instance is created using an Application `Context` and, if the recurrence of this issue is a great concern: off of the UI thread. If these reports are specific to a single OEM or model of device, I suggest testing ADAL in this setting and seeing if the behavior reproduces in your tests.

**Comment by jiaxh** [comment] 2018-03-30 03:33
Hi Brian, Thanks for your reply. 
The initialization has to be in UI thread in our case since some UI elements‘ initialization depends on AAD binded or not;
Strictmode is not on for release build, so I think it's not caused by it;
We are using Application context for the initialization;
Since the anr happens on standard getSharedPreferences call, I'm wondering whether the SharedPreference size can be too big for DefaultTokenCacheStore.

Currently the issue happens not that much, I will keep tracking the trend.

**Comment by iambmelt** [comment] 2018-03-30 17:15
Thanks for the update @jiaxh - keep up in the loop if you start seeing troubling metrics on this.

Let's plan to use IcM/LiveSite to track if this becomes an emerging problem. I'll close this issue. Feel free to get in touch via corpnet email and I can route you to our internal help portal.

/cc @nazukj @danieldobalian

**Closed by iambmelt** 2018-03-30 17:15 UTC
