### ISSUE TITLE
Failed to acquireToken (AUTHORIZATION_CODE_NOT_EXCHANGED_FOR_TOKEN) on Windows Emulator

### ISSUE THREAD

**Issue by MichaelC11** [AzureAD/azure-activedirectory-library-for-android#1398] opened 2019-02-13 01:48 UTC
Hi there!

I'm running a Windows Android Emulator, and I noticed that intermittently, I'd get an error calling
AdalAuthenticationContext.acquireToken, with code AUTHORIZATION_CODE_NOT_EXCHANGED_FOR_TOKEN and message "Error in processing code to get token"

ADAL 1.16.0 with Android OS 28

Do you know what the issue might be?

Thx!!
-Michael

PS: Here's some details, I've set a logger writing to logcat,
public void Log(String tag, String message, String additionalMessage, Logger.LogLevel level, ADALError errorCode) {
                Log.d(..., "[adalLogger]: " + tag + " *** " + message + " *** " + additionalMessage + " *** " + level + " *** " + errorCode);

And here's the relevant snippets,
```
2019-02-12 17:38:26.091 21932-22182 [adalLogger]: Oauth:postMessage ***  [2019-02-13 01:38:26 - 6655d533-a402-4335-b7de-c7e4b2c067e9] SERVER_ERROR:Server returned an error ver:1.16.0 Android 28 *** null *** Error *** SERVER_ERROR
2019-02-12 17:38:26.095 21932-22182 [adalLogger]: Oauth:postMessage ***  [2019-02-13 01:38:26 - 6655d533-a402-4335-b7de-c7e4b2c067e9] SERVER_ERROR:unexpected end of stream on com.android.okhttp.Address@7241f972 ver:1.16.0 Android 28
    java.io.IOException: unexpected end of stream on com.android.okhttp.Address@7241f972
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.microsoft.identity.common.adal.internal.net.HttpWebRequest.send(HttpWebRequest.java:144)
        at com.microsoft.identity.common.adal.internal.net.WebRequestHandler.sendPost(WebRequestHandler.java:74)
        at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:636)
        at com.microsoft.aad.adal.Oauth2.getTokenForCode(Oauth2.java:615)
        at com.microsoft.aad.adal.Oauth2.getToken(Oauth2.java:566)
        at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:101)
        at com.microsoft.aad.adal.AcquireTokenRequest$3.run(AcquireTokenRequest.java:885)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.EOFException: \n not found: size=0 content=...
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26) 
        at com.microsoft.identity.common.adal.internal.net.HttpWebRequest.send(HttpWebRequest.java:144) 
        at com.microsoft.identity.common.adal.internal.net.WebRequestHandler.sendPost(WebRequestHandler.java:74) 
        at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:636) 
        at com.microsoft.aad.adal.Oauth2.getTokenForCode(Oauth2.java:615) 
        at com.microsoft.aad.adal.Oauth2.getToken(Oauth2.java:566) 
        at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:101) 
        at com.microsoft.aad.adal.AcquireTokenRequest$3.run(AcquireTokenRequest.java:885) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by islarrab** [comment] 2019-03-06 22:19
I was getting the same error code and after a lot of digging it turns out it was because the server doesn't like the fact that we are using an Android emulator.

I was using ADAL 1.16.1 and Android Studio's emulator and it was suddenly impossible to log in.

I tested on a physical phone with Android 6.0 and login worked flawlessly.

Anyone care to comment if it's possible to somehow use the emulator for ADAL?

**Comment by Fshiner** [comment] 2019-08-22 08:52
Hi @shoatman is there any update on this issue?
we also met this same issue. The following is the error logs:
E/MRRTAADIdentityProvider: handle login Exception: Error in processing code to get token. CorrelationId: 45a5f2cf-b0c9-42f1-ab31-c42e36398616
E/MRRTAADIdentityProvider: Auth error code: AUTHORIZATION_CODE_NOT_EXCHANGED_FOR_TOKEN
E/MRRTAADIdentityProvider: Failed to get access token
com.microsoft.aad.adal.AuthenticationException: Error in processing code to get token. CorrelationId: 45a5f2cf-b0c9-42f1-ab31-c42e36398616
at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:105)
at com.microsoft.aad.adal.AcquireTokenRequest$3.run(AcquireTokenRequest.java:885)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@544e202d
at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
at com.microsoft.identity.common.adal.internal.net.HttpWebRequest.send(HttpWebRequest.java:144)
at com.microsoft.identity.common.adal.internal.net.WebRequestHandler.sendPost(WebRequestHandler.java:74)
at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:653)
at com.microsoft.aad.adal.Oauth2.getTokenForCode(Oauth2.java:632)
at com.microsoft.aad.adal.Oauth2.getToken(Oauth2.java:583)
at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:101)
at com.microsoft.aad.adal.AcquireTokenRequest$3.run(AcquireTokenRequest.java:885) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
at java.lang.Thread.run(Thread.java:764) 
Caused by: java.io.EOFException: \n not found: size=0 content=...
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244) 
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210) 
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0) 
at com.microsoft.identity.common.adal.internal.net.HttpWebRequest.send(HttpWebRequest.java:144) 
at com.microsoft.identity.common.adal.internal.net.WebRequestHandler.sendPost(WebRequestHandler.java:74) 
at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:653) 
at com.microsoft.aad.adal.Oauth2.getTokenForCode(Oauth2.java:632) 
at com.microsoft.aad.adal.Oauth2.getToken(Oauth2.java:583) 
at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:101) 
at com.microsoft.aad.adal.AcquireTokenRequest$3.run(AcquireTokenRequest.java:885) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
at java.lang.Thread.run(Thread.java:764)

**Comment by hamiltonha** [comment] 2019-11-19 19:15
@iambmelt status?

**Comment by iambmelt** [comment] 2019-11-19 19:17
> @iambmelt status?

#wontfix

**Closed by iambmelt** 2019-11-19 19:17 UTC
Labels: Investigate, bug

**Comment by iambmelt** [comment] 2019-11-19 19:19
> Dupe of: [AzureAD/microsoft-authentication-library-for-android#294](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/294)
> 
> This is a bug in okhttp in combination with the Android Emulator's TCP/IP layer - since our last release (1.16.3) ADAL's http stack has been refactored to share code with MSAL. As a result, this issue is fixed on the `dev` branch and will go out in a future release. For background/root-cause see the above-linked MSAL issue; it appears to be misbehavior related to `Connection: Close`
> 
> I don't have a date available for a next-ADAL release.

Following-up on this post. This workaround did not stick -- after much troubleshooting, this has been diagnosed as an emulator subsystem issue.

Working environments:
•	Physical devices (all platforms)
•	Windows 10 Emulators API 16-18
•	Linux (Debian) Emulators API 16-29
•	MacOS Emulators API 16-29

Non-Working environments:
•	Windows 10 Emulators API 18-29

**Comment by pkgod** [comment] 2019-12-16 09:24
> > Dupe of: [AzureAD/microsoft-authentication-library-for-android#294](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/294)
> > This is a bug in okhttp in combination with the Android Emulator's TCP/IP layer - since our last release (1.16.3) ADAL's http stack has been refactored to share code with MSAL. As a result, this issue is fixed on the `dev` branch and will go out in a future release. For background/root-cause see the above-linked MSAL issue; it appears to be misbehavior related to `Connection: Close`
> > I don't have a date available for a next-ADAL release.
> 
> Following-up on this post. This workaround did not stick -- after much troubleshooting, this has been diagnosed as an emulator subsystem issue.
> 
> Working environments:
> • Physical devices (all platforms)
> • Windows 10 Emulators API 16-18
> • Linux (Debian) Emulators API 16-29
> • MacOS Emulators API 16-29
> 
> Non-Working environments:
> • Windows 10 Emulators API 18-29

any walkaround for this issus?

**Comment by iambmelt** [comment] 2019-12-16 17:52
@pkgod -- only to use one of the listed 'working' environments
