### ISSUE TITLE
Telemetry: When you press back on MFA failure, you get a webview cancel with err_cache_miss error and apps dont know how to handle it

### ISSUE THREAD

**Issue by khalidaw** [AzureAD/azure-activedirectory-library-for-android#712] opened 2016-09-04 12:04 UTC
We see this error a lot in telemetry.

What is the reason for such error and crash (beside changing orientation that we know about)?

**Comment by heidijinxujia** [comment] 2016-09-08 00:41
Hi, where did you see this error? I didn't find it in the Telemetry PR. Thanks.

**Comment by weijjia** [comment] 2016-09-08 00:58
@heidijinxujia I don't think they're talking about the telemetry PR, they observed the error occurrences in their telemetry system. 

@khalidaw err_cache_miss could happen when device running on low memory and the system kills the AuthenticationActivity when it's going background or . If this happens, and activity is re-initialized, it will be restored from the saved state as well as the webview. @heidijinxujia Can you try to repro it if turning on "Don't not keep activities" in the developer options?

**Comment by sdabbiru** [comment] 2016-10-04 01:45
CP telemetry indicates that over 2.5K hit for this error - perhaps a lot of users do MFA. We should address this soon.

**Comment by imakhalova** [comment] 2016-10-18 21:35
Our telemetry shows this error as well.
This message within server response Error Code:-1 net::ERR_CACHE_MISS
sample CorrelationId f6daed14-5831-43ce-9863-d19cf87901f0

**Comment by hjymandroid** [comment] 2016-11-09 19:27
We also see a ton of this 
`com.microsoft.aad.adal.AuthenticationContext.waitingRequestOnError(AuthenticationContext.java:1026)
\tat com.microsoft.aad.adal.AuthenticationContext.onActivityResult(AuthenticationContext.java:900)
\tat com.yammer.droid.ui.login.LoginFragment.onMAMActivityResult(LoginFragment.java:124)
\tat com.microsoft.intune.mam.client.app.offline.OfflineFragmentBehavior.onActivityResult(OfflineFragmentBehavior.java:134)
\tat com.microsoft.intune.mam.client.support.v4.app.MAMFragment.onActivityResult(MAMFragment.java:85)
\tat android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:167)
\tat com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onActivityResultReal(MAMAppCompatActivityBase.java:337)
\tat com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onMAMActivityResult(OfflineActivityBehavior.java:382)
\tat com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onMAMActivityResult(MAMAppCompatActivityBase.java:329)
\tat com.yammer.droid.mam.MAMDelegateAppCompatActivity.onMAMActivityResult(MAMDelegateAppCompatActivity.java:45)
\tat com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onActivityResult(OfflineActivityBehavior.java:372)
\tat com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onActivityResult(MAMAppCompatActivityBase.java:324)
\tat android.app.Activity.dispatchActivityResult(Activity.java:6448)
\tat android.app.ActivityThread.deliverResults(ActivityThread.java:4003)
\tat android.app.ActivityThread.handleSendResult(ActivityThread.java:4050)
\tat android.app.ActivityThread.access$1400(ActivityThread.java:177)
\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)
\tat android.os.Handler.dispatchMessage(Handler.java:102)
\tat android.os.Looper.loop(Looper.java:135)
\tat android.app.ActivityThread.main(ActivityThread.java:5912)
\tat java.lang.reflect.Method.invoke(Native Method)
\tat java.lang.reflect.Method.invoke(Method.java:372)
\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: com.microsoft.aad.adal.AuthenticationException: Error Code:-1 net::ERR_CACHE_MISS CorrelationId: 16b4d0df-6c59-4434-ad17-9509854dc36b
\t... 23 more`

One way to reproduce is to deny the dual authentication(txt,phone,pass) and click back from the authentication page.

**Comment by rknarla** [comment] 2017-02-21 14:31
Even our telemetry shows lot of hits for this web view Error Code:-1 net::ERR_CACHE_MISS
I could repro this issue with MFA enabled. When server calls us back on phone during authentication, do not answer that phone call (neither reject it). Let it timeout or after 2-3 mins, press back button on the device. WebViewClient receives this error.

**Comment by imakhalova** [comment] 2017-02-22 05:44
This is web view issue, can you please create ticket for them. In meanwhile this error should be treated in ADAL as cancel request instead of Error.

**Comment by weijjia** [comment] 2017-03-15 09:00
@imakhalova I don't think it's a webview issue. That's the default behavior of the browser or webview. When navigating back, content is not revalidated, instead the content is just retrieved from the cache. Server sets no-cache which makes sense, one thing we can do is to force the content validation by changing the default cache mode on the webview. @addev-ashish is investigating the possible impact for changing the default cache mode.

**Comment by weijjia** [comment] 2017-03-24 23:06
@addev-ashish checked in a fix for this on 1.12.0.

**Comment by nymerias** [comment] 2017-04-07 21:25
@weijjia @addev-ashish when will 1.12.0 be available? We are currently seeing a spike of this  Error Code:-1 net::ERR_CACHE_MISS issue in our logs for the Yammer Android app as well.

**Comment by imakhalova** [comment] 2017-04-19 19:24
Have you tested it? It's still there for 1.12

**Comment by addev-ashish** [comment] 2017-04-19 20:08
The fix was not made for 1.12.0, it will be a part of the next release. 
@nymerias please quantify "spike", what is the number.

**Comment by weijjia** [comment] 2017-04-19 20:41
@imakhalova Sorry it's my miscommunication with @addev-ashish. Change is checked into dev, but we didn't include it in 1.12.0 release.

**Comment by imakhalova** [comment] 2017-04-19 21:02
ok, thanks for sharing, then we wouldn't expect any change in telemetry then

**Comment by nazukj** [comment] 2018-03-30 00:34
@addev-ashish was this fix checked-in after 1.12.0 release?

**Comment by iambmelt** [comment] 2019-12-19 23:07
Closing due to inactivity

**Closed by iambmelt** 2019-12-19 23:07 UTC
