### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by Eqbalazar** [AzureAD/azure-activedirectory-library-for-android#1076] opened 2017-12-18 15:23 UTC
I am getting error after login , upgrade **ADAL version  from 1.12.0 to 1.13.2**

```java
12-18 09:54:24.153 9842-9930/? E/AndroidRuntime: FATAL EXCEPTION: AcquireTokenRequestHandlerThread
                                                 Process: com.companyname.appname, PID: 9842
                                                 android.view.ViewRootImpl$CalledFromWrongThreadException: 
												 Only the original thread that created a view hierarchy can touch its views.
                                                     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8197)
                                                     at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1268)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.support.v4.widget.DrawerLayout.requestLayout(Unknown Source)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.support.v7.widget.av.requestLayout(Unknown Source)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.view.View.requestLayout(View.java:20084)
                                                     at android.widget.TextView.checkForRelayout(TextView.java:8382)
                                                     at android.widget.TextView.setText(TextView.java:5000)
                                                     at android.widget.TextView.setText(TextView.java:4827)
                                                     at android.widget.TextView.setText(TextView.java:4802)
                                                     at com.companyname.appname.MainActivity.A(Unknown Source)
                                                     at com.companyname.appname.MainActivity.d(Unknown Source)
                                                     at com.companyname.appname.MainActivity$6.a(Unknown Source)
                                                     at com.companyname.appname.MainActivity$6.onSuccess(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenRequest$CallbackHandler$2.run(Unknown Source)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:158)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
12-18 09:54:24.158 2788-3090/? W/ActivityManager:   Force finishing activity com.companyname.appname/.MainActivity
```

**Comment by Eqbalazar** [comment] 2017-12-19 22:00
It is in Background Service :

FileTokenCache _FileTokenCacheStore = new FileTokenCache(getApplicationContext(),
"fileCacheToken.dat");
AuthenticationContext m = new AuthenticationContext(getApplicationContext(),
Constants.AUTHORITY_URL, _FileTokenCacheStore);

**Comment by heidijinxujia** [comment] 2017-12-20 19:04
Thank you for the quick reply. Which adal API you are calling when trying to refresh the token?

**Comment by heidijinxujia** [comment] 2017-12-24 02:17
Hi @Eqbalazar The ADAL API is referring to the function you called in your client app code, not the version number. For exception, are you making an acquireTokenCall? If so, which function are you calling? Thanks.

**Comment by heidijinxujia** [comment] 2018-01-10 18:28
Close the issue because we have not got the reply from customer for more than two weeks. Please feel free to reopen it if you got further question. Thanks.

**Comment by MoBo** [comment] 2018-01-17 11:59
I have the same issue. AuthenticationCallback seem to invoked on a background thread in Version 1.13.3. In Version 1.3.0 the callback was executed on the main thread. Is this the expected behaviour in the new version?

**Comment by iambmelt** [comment] 2018-01-17 21:05
Hello @MoBo @Eqbalazar -- From my testing, I can confirm this as an unintended change that occurred between versions `1.13.1` and `1.13.2`. I will consult with my team and see that a test case is added for future releases.

Reopening this issue, as it's now confirmed.

**Comment by iambmelt** [comment] 2018-01-17 21:06
@nazukj Just putting this on your radar: we can follow-up regarding next steps, milestone, etc.

/cc @heidijinxujia @addev-ashish @piqiums

**Comment by piqiums** [comment] 2018-01-17 21:19
@Eqbalazar, please look at https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/01aae1feeaed724f5fe618a0adf18305b7a987f8/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L878

In the 'AuthenticationCallback<AuthenticationResult> callbackExt', in the method  'onError' & "onSuccess", please update UI on UI Thread via "runOnUiThread". Please don't suppose these 2 callback methods would definitely be called on UI thread.

**Comment by piqiums** [comment] 2018-01-17 21:25
@Eqbalazar , is your app released or still in development? thanks

**Comment by Eqbalazar** [comment] 2018-01-17 21:30
Hi @piqiums  , I tested in Development , I am using 1.13.1 on release .

**Comment by nazukj** [comment] 2018-01-31 21:25
@Eqbalazar, is this working for you with Ping's suggestion?

**Comment by Eqbalazar** [comment] 2018-01-31 21:45
Is working.
Thanks ,

**Closed** 2018-02-01 22:30 UTC
Labels: bug
