### ISSUE TITLE
tokenItem does not contain family refresh token

### ISSUE THREAD

**Issue by caltseng** [AzureAD/azure-activedirectory-library-for-android#1049] opened 2017-11-25 14:02 UTC
We have customers running into the above exception. Any idea what is happening here? It seems like there might be an issue with tokenshare. 

ADAL version - 1.13.1

We have received reports of this on devices with OS 6.0.1 and 7.0.

```
java.lang.IllegalArgumentException: tokenItem does not contain family refresh token
	at com.microsoft.aad.adal.AuthenticationContext.serialize(AuthenticationContext.java:1238)
	at com.microsoft.aad.adal.ADALAuthenticationContext.serialize(ADALAuthenticationContext.java:20)
	at com.microsoft.ols.o365auth.olsauth_android.O365Auth$1.getToken(O365Auth.java:151)
	at com.microsoft.tokenshare.TokenSharingService$TokenProviderBinder.getToken(TokenSharingService.java:296)
	at com.microsoft.tokenshare.ITokenProvider$Stub.onTransact(ITokenProvider.java:63)
	at android.os.Binder.execTransact(Binder.java:573)
```

**Comment by iambmelt** [comment] 2017-12-01 18:00
Under investigation: per conversation w/ @addev-ashish - The `IllegalArgumentException` that is throw in this instance will be changed to a `UsageAuthenticationException`

**Comment by caltseng** [comment] 2017-12-01 18:03
+ @Brian Schnack<mailto:brschn@microsoft.com>

**Comment by nazukj** [comment] 2017-12-07 19:07
Waiting for reply. @iambmelt to ping for update.

**Comment by iambmelt** [comment] 2017-12-08 18:19
While it's still unclear as to how the FRT-less token was persisted for this user, the changes made in #1064 will prevent users from experiencing a crash: if we're unable to find a valid a token for the user they will have to reauthenticate. 

@caltseng do you have strong feelings one way or another about pursuing this issue further to try and pin down a root cause? If not, I suggest we close this issue and reopen if users report experiencing frequent auth prompts.

**Comment by iambmelt** [comment] 2017-12-18 17:49
Email update from @caltseng 

```
1)	This exception is getting thrown when some other app is asking for a token from token share. This means that this exception does not seem to be affecting StaffHub but may be negatively impacting another Microsoft App. 
2)	Catching the exception will result in getToken() returning null. I have verified in TokenManager that returning null for getToken() is an expected case. This means that other apps should be gracefully handling this, as if there were no other tokens found. 
3)	PR for this change is here: <omitted>

I plan to bundle this in with our next release, given that this seems to be a low-risk fix.  

Thanks, 
CalebT
```

Closing this issue to reopen with separate issue for investigation. Will provide link here.

**Closed by iambmelt** 2017-12-18 17:49 UTC
Labels: bug, Investigating
