### ISSUE TITLE
android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.webkit.WebView

### ISSUE THREAD

**Issue by caltseng** [AzureAD/azure-activedirectory-library-for-android#771] opened 2017-02-10 18:01 UTC
Android: 6.0
Android Build: VNS-L21C432B160
Manufacturer: HUAWEI
Model: HUAWEI VNS-L21
Thread: main-1
CrashReporter Key: 2FCAF74C-20C4-B6F6-A4F1-A6FD90B41ECE8F3F4682
Start Date: Fri Feb 10 12:04:56 GMT+01:00 2017
Date: Fri Feb 10 12:05:49 GMT+01:00 2017

java.lang.RuntimeException: Unable to start activity ComponentInfo{ols.microsoft.com.shiftr/com.microsoft.aad.adal.AuthenticationActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.webkit.WebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2479)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.inflate(LayoutInflater.java:561)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
	at android.transition.Scene.enter(Scene.java:175)
	at com.android.internal.policy.PhoneWindow.transitionTo(PhoneWindow.java:486)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:426)
	at android.app.Activity.setContentView(Activity.java:2221)
	at com.microsoft.aad.adal.AuthenticationActivity.onCreate(AuthenticationActivity.java:152)
	at android.app.Activity.performCreate(Activity.java:6372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
	... 9 more
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:672)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:721)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:789)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Constructor.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:641)
	... 27 more
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:211)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:158)
	at android.webkit.WebView.getFactory(WebView.java:2277)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2272)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2331)
	at android.view.View.<init>(View.java:3846)
	at android.view.View.<init>(View.java:3949)
	at android.view.ViewGroup.<init>(ViewGroup.java:573)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:597)
	at android.webkit.WebView.<init>(WebView.java:542)
	at android.webkit.WebView.<init>(WebView.java:525)
	at android.webkit.WebView.<init>(WebView.java:512)
	... 29 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
	at android.webkit.WebViewFactory.fetchPackageInfo(WebViewFactory.java:109)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:183)
	... 41 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:154)
	at android.webkit.WebViewFactory.fetchPackageInfo(WebViewFactory.java:107)
	... 42 more

**Comment by weijjia** [comment] 2017-03-24 22:31
@caltseng can you get us more info? The full logs might help. This looks like the os is trying to find the com.google.android.webview, and it's unable to find it.

**Comment by nazukj** [comment] 2017-04-07 18:55
Closing issue since we can't repro and don't have logs/repro steps. Please feel free to re-open issue with relevant information requested. Thanks!

**Closed by nazukj** 2017-04-07 18:55 UTC
Labels: External, p3

**Comment by LesterTheTester** [comment] 2017-04-12 18:57
Hi, we have a very similar issue.  We only started seeing this exception in our production app once we raised our targetSdkVersion to 25 and our build tools to 25.0.2.  

Package: com.yammer.v1
Version Code: 1341
Version Name: 5.4.14.1341
Android: 7.0
Android Build: NRD90M release-keys
Manufacturer: HTC
Model: HTC One M9
Thread: main-1
CrashReporter Key: 29099BE0-04F6-CEA5-77F3-A638DA1289AE189E8E87
Start Date: Wed Apr 12 11:44:52 EDT 2017
Date: Wed Apr 12 11:45:28 EDT 2017

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yammer.v1/com.microsoft.aad.adal.AuthenticationActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.webkit.WebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2729)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2790)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at android.transition.Scene.enter(Scene.java:175)
	at com.android.internal.policy.PhoneWindow.transitionTo(PhoneWindow.java:500)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:431)
	at android.app.Activity.setContentView(Activity.java:2423)
	at com.microsoft.aad.adal.AuthenticationActivity.onCreate(AuthenticationActivity.java:152)
	at android.app.Activity.performCreate(Activity.java:6673)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2790)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 298713250 actual: 288309150
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
	at android.webkit.WebView.getFactory(WebView.java:2324)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2319)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2378)
	at android.view.View.<init>(View.java:4014)
	at android.view.View.<init>(View.java:4131)
	at android.view.ViewGroup.<init>(ViewGroup.java:578)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:626)
	at android.webkit.WebView.<init>(WebView.java:571)
	at android.webkit.WebView.<init>(WebView.java:554)
	at android.webkit.WebView.<init>(WebView.java:541)
	... 29 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 298713250 actual: 288309150
	at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:243)
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:303)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
	... 41 more

**Comment by MrPresident96** [comment] 2019-04-05 20:30
Hi everyone. I have the same problem. There is my full logs

**Comment by MrPresident96** [comment] 2019-04-05 20:30
I/WebViewFactory: Loading com.google.android.webview version 37 (1602158-arm) (code 111201)
I/LibraryLoader: Loading: webviewchromium
    Time to load native libraries: 4 ms (timestamps 6901-6905)
    Expected native library version number "",actual native library version number ""
V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {ad73b14}
I/LibraryLoader: Expected native library version number "",actual native library version number ""
I/chromium: [INFO:library_loader_hooks.cc(106)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController: Initializing chromium process, renderers=0
W/art: Attempt to remove local handle scope entry from IRT, ignoring
W/AudioManagerAndroid: Requires BLUETOOTH permission
W/chromium: [WARNING:resource_bundle.cc(315)] locale_file_path.empty()
I/chromium: [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=71 off=43792 len=2945
    [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:72 off:229540 len:643667
W/chromium: [WARNING:proxy_service.cc(901)] PAC support disabled because there is no system implementation
W/chromium: [WARNING:data_reduction_proxy_settings.cc(403)] SPDY proxy OFF at startup
W/ResourceType: No known package when getting value for resource number 0x04040002
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uz.shopix.shop, PID: 26867
    android.view.InflateException: Binary XML file line #8: Error inflating class android.webkit.WebView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at uz.shopix.shop.main.fragment.TechnicalHelpFragment.onCreateView(TechnicalHelpFragment.kt:26)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2539)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1227)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:710)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2063)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1808)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1715)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:143)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:155)
        at android.app.ActivityThread.main(ActivityThread.java:5696)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at uz.shopix.shop.main.fragment.TechnicalHelpFragment.onCreateView(TechnicalHelpFragment.kt:26) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2539) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:875) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1227) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:710) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2063) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1808) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1715) 
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:143) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:155) 
        at android.app.ActivityThread.main(ActivityThread.java:5696) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x4040002
        at android.content.res.Resources.getText(Resources.java:286)
        at android.content.res.Resources.getString(Resources.java:372)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:702)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:619)
        at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:758)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:608)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:546)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:97)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:124)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:111)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:108)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
        at android.webkit.WebView.<init>(WebView.java:548)
        at android.webkit.WebView.<init>(WebView.java:483)
    	at android.webk
D/Process: killProcess, pid=26867
D/Process: com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 
Application terminated.
