### ISSUE TITLE
Acquire token silent doesn't accept email as userId

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#630] opened 2016-05-19 00:04 UTC
Why acquire token accepts email as userId and silent request accepts guid?
What is the point to make user aware of his adal unique id while he has dispayable id?
Looks like iOS ADAL accepts email for silent requests...

**Comment by nazukj** [comment] 2017-03-31 22:56
The API is inconsistent as per requirement of the Broker. This will be fixed in V2 major release. By Design.

**Closed by nazukj** 2017-03-31 22:56 UTC
